# Generated by Django 5.0.2 on 2024-02-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='code',
            new_name='color',
        ),
    ]
