# Generated by Django 5.0.2 on 2024-02-24 05:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_code_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#ff0000', 'qizil'), ('#FFFEFA', 'oq'), ('#ffff00', 'sariq'), ('#008000', 'yashil'), ('#0000ff', "ko'k"), ('#4b0082', 'binafsha'), ('#ee82ee', 'pushti'), ('#000000', 'qora')]),
        ),
    ]
