# Generated by Django 5.0.2 on 2024-03-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_color_color'),
        ('product', '0003_alter_color_color'),
    ]

    operations = [
    ]
