# Generated by Django 4.2.10 on 2024-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
