# Generated by Django 5.0.2 on 2024-03-07 17:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_0002_alter_color_color_0003_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#ff0000', 'qizil'), ('#FFFEFA', 'oq'), ('#ffff00', 'sariq'), ('#008000', 'yashil'), ('#0000ff', "ko'k"), ('#4b0082', 'binafsha'), ('#ee82ee', 'pushti'), ('#000000', 'qora')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('HOT', 'HOT'), ('NEW', 'NEW'), ('OLD', 'OLD'), ('TOP', 'TOP'), ('SALE', 'SALE'), ('DISCOUNT', 'DISCOUNT')], default='HOT', max_length=300),
        ),
    ]
