# Generated by Django 4.2.10 on 2024-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(default=1, upload_to='brand/'),
            preserve_default=False,
        ),
    ]
