# Generated by Django 4.2.10 on 2024-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_brand_img_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('HOT', 'HOT'), ('NEW', 'NEW'), ('SALE', 'SALE')], default='HOT', max_length=250),
        ),
    ]
