# Generated by Django 4.2.10 on 2024-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_numeber',
            new_name='phone_number',
        ),
    ]
