# Generated by Django 4.2.10 on 2024-03-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_address_order_email_order_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
