# Generated by Django 4.2.10 on 2024-03-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
